### ISSUE TITLE
Neovimへの対応

### ISSUE THREAD

**Issue by supermomonga** [mikoto2000/devcontainer.vim#46]
VimだけでなくNeovimにも対応されていると嬉しいです。

Neovim公式リポジトリで配布されているビルド済みバイナリにはaarch64用が存在しないこと、Apple Silicon対応を考慮する場合はソースからのビルドが必要になるかと思います。（現状公開されているDev Container Featuresにもソースからビルドするものは無し）

---

ref: `remote-nvim.nvim` のインストールスクリプト
https://github.com/amitds1997/remote-nvim.nvim/blob/main/scripts/neovim_install.sh

**Comment by mikoto2000** [comment]
リクエストありがとうございます！
何段階かに分けて対応したいですね。

1. Vim と同じくコンソール版での対応(x86_64のみ)
    - AppImage で配布されているので、比較的簡単に実現可能なはず
    - クリップボード連携が Vim と別実装での通信が必要になるか？
2. NeoVim のクライアント/サーバーの仕組みを使った対応(x86_64のみ)
    - ポートの繋ぎ込みが大変そう
    - GUI 実装がたくさんあるので対応が大変そう
3. Apple Silicon(ARM) 対応(不可能なのでは？)
    - AppImage は aarch64 に対応していない
    - NeoVim はスタティックリンクビルドができない
    - という 2 点から不可能なのではと思っている
 
以上思いついたまま書いてしまいましたが、やれるところからやってみてみます。

**Comment by mikoto2000** [comment]
第一ステップの派生 issue を作成 #49

**Comment by mikoto2000** [comment]
コンソール版 NeoVim を起動可能にしたバージョン v3.0.0 をリリース。
※ ただし、クリップボード連携はまだ動かない
https://github.com/mikoto2000/devcontainer.vim/releases/tag/v3.0.0

**Comment by supermomonga** [comment]
@mikoto2000 爆速対応ありがとうございます！

**Comment by supermomonga** [comment]
> NeoVim はスタティックリンクビルドができない

この点、ビルド済みAppImageを設置するのではなく、Dev Container内でビルドする方式だと解決できるのでしょうか？ もしそうであれば、「aarch64環境ではソースからビルドし、そうでなければAppImageをダウンロードし配置する」という内容のDev Container Featureを作成し、`--override-config` に渡す動的に生成する `devcontainer.json` ファイルの `features` にそちらを差し込む形での解決というアプローチはありでしょうか？

ソースからビルドする場合、Linuxディストリビューションごとにパッケージマネージャが異なるのでスクリプトの保守メンテが大変そう・Neovimのためだけに意図しないパッケージのインストールが行われてしまう、という問題はありそうですが…

**Comment by mikoto2000** [comment]
なるほど、アリだと思います。

`features` を作るのが難しそうだというのが心配ですが、それをクリアすれば devcontainer.vim 側での対応は比較的楽だと思います。

devcontainer.vim 側の処理としては、「`features` を作るなり、自分で Dockerfile を作ってインストールするなり、何かしらの方法でシステムに `nvim` が入っているならそれを使い、そうでないなら `vim` にフォールバックする」という挙動にすればいい感じになりそうです。

**Comment by mikoto2000** [comment]
トピックの整理ありがとうございます。

> feature機能やDockerfile内の処理などでVim/Neovimが既にインストールされていた場合、devcontainer.vimが持つインストール処理はスキップする（独自にパッチを当てたNeovim/Vimを使いたい人などにも有用）

こちらは比較的簡単そうですので、優先して別 issue で着手しようと思います。

**Comment by mikoto2000** [comment]
> feature機能やDockerfile内の処理などでVim/Neovimが既にインストールされていた場合、devcontainer.vimが持つインストール処理はスキップする（独自にパッチを当てたNeovim/Vimを使いたい人などにも有用）

これについて、#55 で対応完了。

**Comment by mikoto2000** [comment]
[Release v3.1.0 · mikoto2000/devcontainer.vim](https://github.com/mikoto2000/devcontainer.vim/releases/tag/v3.1.0) でリリース。

**Comment by mikoto2000** [comment]
インストールさえできてしまえばよいことになったので、以下ページの NeoVim feature が使えるかもしれない。
https://containers.dev/features

**Comment by mikoto2000** [comment]
> 1.    Vim と同じくコンソール版での対応(x86_64のみ)
        AppImage で配布されているので、比較的簡単に実現可能なはず
        クリップボード連携が Vim と別実装での通信が必要になるか？
>  2.   NeoVim のクライアント/サーバーの仕組みを使った対応(x86_64のみ)
        ポートの繋ぎ込みが大変そう
        GUI 実装がたくさんあるので対応が大変そう
> 3.   Apple Silicon(ARM) 対応(不可能なのでは？)
        AppImage は aarch64 に対応していない
        NeoVim はスタティックリンクビルドができない
        という 2 点から不可能なのではと思っている

「1.」と「3.」を実現できたので、本 issue としてはクローズします。
(3 についてはワークアラウンドっぽいですが)

「2.」や「Dev Container Features」については、要望があれば改めて別 issue 年て作成をお願いいたしいます。

**Comment by supermomonga** [comment]
@mikoto2000 ありがとうございます！
