### ISSUE TITLE
go install コマンドでv2以上のリリースタグを解決できない

### ISSUE THREAD

**Issue by supermomonga** [mikoto2000/devcontainer.vim#52]
```sh
go clean -cache && go install github.com/mikoto2000/devcontainer.vim@latest # => v1.3.1が解決される

go install github.com/mikoto2000/devcontainer.vim@v1.3.1 # => 成功

go install github.com/mikoto2000/devcontainer.vim@v2.0.0 # => 失敗
# go: github.com/mikoto2000/devcontainer.vim@v2.0.0: github.com/mikoto2000/devcontainer.vim@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/mikoto2000/devcontainer.vim/v2")

go install github.com/mikoto2000/devcontainer.vim@v3.0.0 # => 失敗
# go: github.com/mikoto2000/devcontainer.vim@v3.0.0: github.com/mikoto2000/devcontainer.vim@v3.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/mikoto2000/devcontainer.vim/v3")
```

ref: https://research.swtch.com/vgo-import
ref: https://christina04.hatenablog.com/entry/go-modules-major-version

https://github.com/mikoto2000/devcontainer.vim/blob/f76a8002705cc7a3096e6176a13e43aa1de3a00e/go.mod#L1

Goは触ったことがないのであまり自信はありませんが、`go.mod`のmodule指定に末尾 `/v3` などのメジャーバージョンが指定されていないため、v1と見做されてしまい、実際のリリースタグとの不一致でエラーとなるのではないか、と考えています。

**Comment by mikoto2000** [comment]
なるほど、自分も雰囲気で使っていたのでこれ知りませんでした...。
ありがとうございます、対応します。
(古いバージョンがインストールできないのはそのままになってしまいそうですが...)

**Comment by mikoto2000** [comment]
#53  で対応完了。

**Comment by mikoto2000** [comment]
latest ではインストールできるが、バージョン指定ではインストールできない...何故だ？

**Comment by mikoto2000** [comment]
あ、タグが無いからか、リリース後、v3.0.2 からバージョン指定でのインストールが可能になる(はず)

**Comment by mikoto2000** [comment]
ビルドに失敗している...。こういう時に限ってローカルで試すのをサボるんですよねぇ...

[Bumped up to 3.0.2. · mikoto2000/devcontainer.vim@468db7b](https://github.com/mikoto2000/devcontainer.vim/actions/runs/12114461726/job/33771057714#step:4:7)

**Comment by mikoto2000** [comment]
23e15db296aebd6a952623863e982b6d5ac3c625, de86dc02f6fa14bd7049bfbfa2cd02308fde0485 で対応完了。
指摘ありがとうございました！

**Comment by supermomonga** [comment]
@mikoto2000 ありがとうございます！ただ、私の環境だと意図通りにバージョン解決されず…

```sh
go clean -modcache && GOPROXY=direct go install github.com/mikoto2000/devcontainer.vim@latest
# => v1.3.1 が解決

go clean -modcache && GOPROXY=direct go install github.com/mikoto2000/devcontainer.vim@v3.0.2
# => 失敗
# go: github.com/mikoto2000/devcontainer.vim@v3.0.2: github.com/mikoto2000/devcontainer.vim@v3.0.2: invalid version: go.mod has post-v3 module path "github.com/mikoto2000/devcontainer.vim/v3" at revision v3.0.2
```

**Comment by supermomonga** [comment]
あっ、バージョン指定時は `go install github.com/mikoto2000/devcontainer.vim/v3@v3.0.2` の様に指定しないとだめなんですね。
`v3@latest` `v3@v3.0.2` どちらの指定でも最新版をインストールすることができました！

**Comment by mikoto2000** [comment]
@supermomonga あ、そこ自分も戸惑いましたが、 `@` の前にも `/v3` が必要です。

```sh
go install github.com/mikoto2000/devcontainer.vim/v3@3.0.2
```

と、書いているうちに解決したようですね。よかったです。

**Comment by supermomonga** [comment]
@mikoto2000 ありがとうございます 🙏
