### ISSUE TITLE
ホストマシンがApple Siliconのmac端末の場合、コンテナ内システムインストールNeovimの利用ができない

### ISSUE THREAD

**Issue by supermomonga** [mikoto2000/devcontainer.vim#57]
`tools/nvim_darwin_arm64.go` の実装がVimを利用する内容となっているため、ホストマシンがApple Siliconのmac端末である場合、以下のような問題が発生していそうです。

- コンテナにNeovimがシステムインストールされている場合でも `vim` コマンドを探してしまい、インストールされていない判定になってしまう
- `devcontainer exec` で `nvim` ではなく `vim` コマンドを実行してしまう

**Comment by mikoto2000** [comment]
`tools/nvim_darwin_arm64.go` は、フォールバックのためにツール名を `vim` のままにしていたが、それだとシステムインストールエディタ確認の際に `vim` を確認しに行ってしまう。

パッと思いつく修正案は以下ふたつ。

1. ツール名を `nvim` に変更する → ホストのキャッシュに `vim` , `nvim` という名前の同一ファイル(実態は `vim`) ができてしまう
2. システムインストールエディタ判定を見直す → ツール定義構造体とは別にエディタ名を管理することになるので複雑化しそう

昨今はストレージ単価も安くなっていることだし、「1.」の方針で修正することとしたい。

**Comment by mikoto2000** [comment]
単純に `nvim` にするだけだと、システムインストールの `nvim` が見つからなかった際に `vim` を起動するときに `SendToTCP.lua` を `vim` に渡してしまうことになる...
ツール名を見て制御するのではなく、ちゃんとフラグを見て制御するように修正しないとダメそう。

**Comment by mikoto2000** [comment]
Pull Request を作り忘れてしまった...。

[Release v3.2.1 · mikoto2000/devcontainer.vim](https://github.com/mikoto2000/devcontainer.vim/releases/tag/v3.2.1) で対応完了。

**Comment by supermomonga** [comment]
@mikoto2000 ありがとうございます！
