### ISSUE TITLE
ホストマシンとコンテナのCPUアーキテクチャが必ずしも一致しない

### ISSUE THREAD

**Issue by supermomonga** [mikoto2000/devcontainer.vim#58]
## 概要

DockerfileのFROM指定およびdockerコンテナ起動時の引数に platform を指定することで、ホストマシンと異なるCPUアーキテクチャのコンテナを実行することができます。

e.g.)
- Dockerfile: `FROM --platform=linux/amd64 ruby`
- devcontainer.json: `"runArgs": ["--platform=linux/amd64"]`

現在、コンテナに転送するツールはホストマシンのCPUアーキテクチャによって決定されていますが、ホストマシンとコンテナのCPUアーキテクチャが必ずしも一致しないため、コンテナのCPUアーキテクチャによって決定できると良さそうに思います。

## コンテナのCPUアーキテクチャ取得方法の調査

```sh
docker run --rm -it --platform linux/x86_64 denoland/deno deno repl
```

![CleanShot 2024-12-03 at 11 24 47](https://github.com/user-attachments/assets/25504071-3a7a-4375-a9ea-51cfd6357005)

画像のようにDocker Desktopではplatformの検出が行われているのですが、クローズドソースのためどの用にして検出しているのか調査しきれていません。

少なくとも `docker inspect` コマンドの結果にはエミュレーション周りの情報がなさそうに見えます。
（`Platform` プロパティがそれっぽいかなと思ったのですが単に `linux` となっておりCPUアーキテクチャは含まれていなさそう）

```sh
$ docker inspect 4f138061da85afadf18a7957dc64e5e2cb91af398812fab040f1b63f4f7fb700 | jq '.[0].Platform'
"linux"
```

**Comment by mikoto2000** [comment]
`uname` のあるコンテナであれば、 `docker exec <container_id> uname -m` で取得できますね。
開発用コンテナで `uname` が無いコンテナを利用するなんて過酷なことをする人はいないと思いますので、この判定方法で良いかもしれません。

**Comment by mikoto2000** [comment]
現状はホストとコンテナが同じ ARCH であるという前提の設計となっているため、比較的大規模な構成変更が必要。

- `xxx_arm64.go` となっているものは `xxx.go` に変更し、ARCH を判定して出し分けるように修正
- プログラム開始直後にバイナリダウンロードを行っているが、 ARCH がわかるのがコンテナを起動した後なのでダウンロードタイミングを修正

**Comment by supermomonga** [comment]
`docker image inspect [IMAGE]` 内にありました！ uname などのコマンドに依存せず取得できそうです！

```sh
$ docker inspect bd427ed09808be5183ce482d3ee9cfbda82d718d5417040ce692f8931fa0b6b8 | jq '.[0].Image'
"sha256:ffbf322e0c89d8900c18108ba362920f572e4ea109c7df37870ecaeeaa53aab7"

$ docker image inspect ffbf322e0c89d8900c18108ba362920f572e4ea109c7df37870ecaeeaa53aab7 | jq '.[0] | {Os: .Os, Architecture: .Architecture}'
{
  "Os": "linux",
  "Architecture": "amd64"
}
```

**Comment by supermomonga** [comment]
> ARCH がわかるのがコンテナを起動した後なのでダウンロードタイミングを修正

`docker image inspect` で特定できることがわかったので、イメージのIDが特定できればコンテナを起動せず判定できそうです

**Comment by supermomonga** [comment]
Dockerfile内からビルド時に判定したい場合は環境変数 `BUILDPLATFORM` と `TARGETPLATFORM` が使えそうです。

https://docs.docker.com/build/building/multi-platform/#cross-compilation

これはFeatureを作る時に使えそうですね

**Comment by mikoto2000** [comment]
M1 Mac で x86_64 のコンテナ起動しても、 AppImage は実行できないようですね...。
これもスタティックリンク Vim に置き換える形になりそう。

**Comment by mikoto2000** [comment]
ひとまず `which` を使う実装が簡単なのでそれで実装完了。
Linux での動作確認完了。
M1 Mac での動作確認中。
README に環境と実行する Vim/NeoVim の関係をまとめないと...

**Comment by mikoto2000** [comment]
あ、 M1 Mac の nvim AppImage も動かないのか...。
今度はこっちを vim-static にフォールバックしないと。

**Comment by mikoto2000** [comment]
整理するとこう。
本当はホストの ARCH まで分岐しないといけないけど arm の Win も Linux も持っていないので無理。
![image](https://github.com/user-attachments/assets/c315ddbe-9b73-47a5-959e-e07db36c6502)

**Comment by mikoto2000** [comment]
Limitation としては

- macOS で NeoVim を利用する場合はシステムインストールされたものを利用する必要がある
- aarch64 のコンテナで NeoVim を利用する場合はシステムインストールされたものを利用する必要がある
- NeoVim AppImage が使えず、システムインストールの NeoVim も存在しない場合、 NeoVim の代わりに Vim が起動する

という感じか。

**Comment by supermomonga** [comment]
調査ありがとうございます。めちゃくちゃややこしいですね…

**Comment by mikoto2000** [comment]
start コマンドばかり確認して run コマンドのことを忘れていた。今から実装します。

**Comment by mikoto2000** [comment]
#60 で対応。

**Comment by mikoto2000** [comment]
[Release v3.3.0 · mikoto2000/devcontainer.vim](https://github.com/mikoto2000/devcontainer.vim/releases/tag/v3.3.0) でリリースしました。

**Comment by supermomonga** [comment]
@mikoto2000 ありがとうございます！
